# Generated by Django 3.2 on 2022-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Order Received', 'Order Received'), ('Delivered', 'Delivered')], default='Order Received', max_length=50),
        ),
    ]
