# Generated by Django 3.2 on 2022-02-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20220223_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='total',
        ),
    ]
