# Generated by Django 3.2 on 2022-03-04 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='material',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
