# Generated by Django 3.2 on 2022-02-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('1', 'no'), ('2', '10% discount'), ('3', '20% discount')], default=1, max_length=100),
        ),
    ]
