# Generated by Django 3.2 on 2022-03-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_user'),
        ('products', '0006_auto_20220318_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accounts.account'),
        ),
    ]
